customhost = "employee.cnmmb1xzwoxd.ap-south-1.rds.amazonaws.com"
customuser = "Rushikesh"
custompass = "rushi1990"
customdb = "employee"
custombucket = "addemployeeinstorage"
customregion = "ap-south-1b"
